### PR TITLE
Added Colors Protection checks which run at plugin start

### PR DESCRIPTION
**Pull request by SeveralCircles**
Added protection features to prevent plugin from being run in environments and in ways not intended. If any protection checks fail, the plugin will not load. Checks implemented with this pull request include:

- BuildExpiry - Prevents plugin from being run more than 30 days after build date, thereby requiring the user to update the plugin from an official source.
- RunViaSpigot - Prevents plugin from being run by the JAR it comes in, instead requiring the user to run it through a Spigot or Bukkit server

The framework is currently open for more checks to be implemented.

### CODE REVIEW

**Comment by SeveralCircles** [comment]
Codacy Here is an overview of what got changed by this pull request:


```diff

Issues
======
- Added 6
           

Complexity increasing per file
==============================
- src/com/severalcircles/colors/system/protection/RunViaSpigot.java  1
- src/com/severalcircles/colors/system/protection/ProtectionCheck.java  3
- src/com/severalcircles/colors/system/protection/ProtectionCheckFailException.java  2
- src/com/severalcircles/colors/system/protection/BuildExpiry.java  6
- src/com/severalcircles/colors/system/Main.java  6
         

Clones added
============
- src/com/severalcircles/colors/system/protection/BuildExpiry.java  1
- src/com/severalcircles/colors/system/Main.java  1
         
```


See the complete overview on [Codacy](https://app.codacy.com/manual/aidanveney/colors/pullRequest?prid=5538765&bid=18156492)

**Review by BeegBrainMo — APPROVED** [review]
Looks alright, I don't see any problems. But then again I'm not that experienced in coding.

**Comment by SeveralCircles** [comment]
Codacy Here is an overview of what got changed by this pull request:


```diff

Issues
======
- Added 4
           

Complexity increasing per file
==============================
- src/com/severalcircles/colors/system/protection/RunViaSpigot.java  1
- src/com/severalcircles/colors/system/protection/ProtectionCheckFailException.java  2
- src/com/severalcircles/colors/system/protection/ProtectionCheck.java  3
- src/com/severalcircles/colors/system/protection/BuildExpiry.java  6
- src/com/severalcircles/colors/system/Main.java  6
         

Clones added
============
- src/com/severalcircles/colors/system/protection/BuildExpiry.java  1
- src/com/severalcircles/colors/system/Main.java  1
         
```


See the complete overview on [Codacy](https://app.codacy.com/manual/aidanveney/colors/pullRequest?prid=5538765&bid=18156492)

**Review by Minotaurinmaze — APPROVED** [review]
It looks good!

**Pull request merged**
