### PR TITLE
Develop

### PR DESCRIPTION
**Pull request by SeveralCircles**
Added some very spicy "easter eggs".

### CODE REVIEW

**Comment by Minotaurinmaze** [comment]
no

**Comment by Minotaurinmaze** [comment]
sans

**Comment by BeegBrainMo** [comment]
Funny haha ettinger

**Review by Minotaurinmaze — COMMENTED** [review]
What does it do.

**Review by BeegBrainMo — APPROVED** [review]
thicc

**Comment by SeveralCircles** [comment]
> 
> 
> What does it do.

nothing

**Review by Minotaurinmaze — APPROVED** [review]
It does nothing. You got the OK from me. :\

**Pull request merged**
