### PR TITLE
Release Red 2

### LINKED ISSUE #7: "Persona" command doesn't show it's output to anybody but the player.

### PR DESCRIPTION
**Pull request by SeveralCircles**
Adds the following features:
- The plugin now works
- About command
- Persona command

### CODE REVIEW

**Comment by SeveralCircles** [comment]
Codacy Here is an overview of what got changed by this pull request:


```diff

Complexity increasing per file
==============================
- src/com/severalcircles/colors/commands/CommandPersona.java  2
- src/com/severalcircles/colors/commands/CommandAbout.java  1
         
```


See the complete overview on [Codacy](https://app.codacy.com/manual/aidanveney/colors/pullRequest?prid=5526468&bid=18113216)

**Comment by SeveralCircles** [comment]
We should resolve #7 before merging this, unless that behaviour is intended.

**Comment by SeveralCircles** [comment]
Codacy Here is an overview of what got changed by this pull request:


```diff

Issues
======
- Added 2
           

Complexity increasing per file
==============================
- src/com/severalcircles/colors/commands/CommandPersona.java  2
- src/com/severalcircles/colors/commands/CommandAbout.java  1
         
```


See the complete overview on [Codacy](https://app.codacy.com/manual/aidanveney/colors/pullRequest?prid=5526468&bid=18113216)

**Comment by SeveralCircles** [comment]
Codacy Here is an overview of what got changed by this pull request:


```diff

Complexity increasing per file
==============================
- src/com/severalcircles/colors/commands/CommandPersona.java  2
- src/com/severalcircles/colors/commands/CommandAbout.java  1
         
```


See the complete overview on [Codacy](https://app.codacy.com/manual/aidanveney/colors/pullRequest?prid=5526468&bid=18113216)

**Comment by SeveralCircles** [comment]
Codacy Here is an overview of what got changed by this pull request:


```diff

Complexity increasing per file
==============================
- src/com/severalcircles/colors/commands/CommandNedry.java  2
- src/com/severalcircles/colors/commands/CommandAbout.java  1
- src/com/severalcircles/colors/commands/CommandPersona.java  2
         
```


See the complete overview on [Codacy](https://app.codacy.com/manual/aidanveney/colors/pullRequest?prid=5526468&bid=18113216)

**Review by BeegBrainMo — APPROVED** [review]
Looks like everything is okie dokie

**Comment by SeveralCircles** [comment]
Codacy Here is an overview of what got changed by this pull request:


```diff

Complexity increasing per file
==============================
- src/com/severalcircles/colors/commands/CommandPersona.java  2
- src/com/severalcircles/colors/commands/CommandAbout.java  1
- src/com/severalcircles/colors/commands/CommandNedry.java  2
         
```


See the complete overview on [Codacy](https://app.codacy.com/manual/aidanveney/colors/pullRequest?prid=5526468&bid=18113216)

**Review by Minotaurinmaze — APPROVED** [review]
The files do be looking good though.

**Pull request merged**
